### ISSUE TITLE
sway fcitx5 chinese candidate prompt window not showing 

### ISSUE THREAD

**Issue by weihua-lu** [fcitx/fcitx5#535]
# two issues observed with sway+fcitx5
1. With sway, wayland and latest emacsPgtkNativeComp, when I first open emacs and type Chinese, everything looks ok, the candidate prompt window is showing as normal. But after I switch workspace and switch back to emacs(or even switch focus to another window and switch back), typing Chinese and the candidate prompt window no longer shows. Open a new instance of emacs, everything works again until I switch focus.
2. Tried another app, gnome-terminal. For this one, candidate prompt never shows up from beginning.

`sway version 1.7`
`GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0)`
`GNOME Terminal 3.44.1 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD`

# System Info:
1.  `uname -a`:

        Linux ge 5.18.6 #1-NixOS SMP PREEMPT_DYNAMIC Wed Jun 22 12:28:13 UTC 2022 x86_64 GNU/Linux

2.  `lsb_release`:

    `lsb_release` not found.

3.  `/etc/lsb-release`:

        DISTRIB_CODENAME=raccoon
        DISTRIB_DESCRIPTION="NixOS 22.11 (Raccoon)"
        DISTRIB_ID=nixos
        DISTRIB_RELEASE="22.11"
        LSB_VERSION="22.11 (Raccoon)"

4.  `/etc/os-release`:

        BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
        BUILD_ID="22.11.20220629.cf3ab54"
        DOCUMENTATION_URL="https://nixos.org/learn.html"
        HOME_URL="https://nixos.org/"
        ID=nixos
        LOGO="nix-snowflake"
        NAME=NixOS
        PRETTY_NAME="NixOS 22.11 (Raccoon)"
        SUPPORT_URL="https://nixos.org/community.html"
        VERSION="22.11 (Raccoon)"
        VERSION_CODENAME=raccoon
        VERSION_ID="22.11"

5.  Desktop Environment:

    Cannot determine desktop environment.

6.  XDG SESSION TYPE:

        XDG_SESSION_TYPE='wayland'

7.  Bash Version:

        BASH_VERSION='5.1.16(1)-release'

# Environment:
1.  DISPLAY:

        DISPLAY=':0'

        WAYLAND_DISPLAY='wayland-1'

2.  Keyboard Layout:

    1.  `setxkbmap`:

        `setxkbmap` not found.

    2.  `xprop`:

        `xprop` not found.

3.  Locale:

    1.  All locales:

            C
            en_US.utf8
            POSIX
            zh_CN
            zh_CN.gb18030
            zh_CN.gb2312
            zh_CN.gbk
            zh_CN.utf8
            zh_TW
            zh_TW.big5
            zh_TW.utf8

    2.  Current locale:

            LANG=en_US.UTF-8
            LC_CTYPE="en_US.UTF-8"
            LC_NUMERIC="en_US.UTF-8"
            LC_TIME="en_US.UTF-8"
            LC_COLLATE="en_US.UTF-8"
            LC_MONETARY="en_US.UTF-8"
            LC_MESSAGES="en_US.UTF-8"
            LC_PAPER="en_US.UTF-8"
            LC_NAME="en_US.UTF-8"
            LC_ADDRESS="en_US.UTF-8"
            LC_TELEPHONE="en_US.UTF-8"
            LC_MEASUREMENT="en_US.UTF-8"
            LC_IDENTIFICATION="en_US.UTF-8"
            LC_ALL=

4.  Directories:

    1.  Home:

            /home/weihua

    2.  `${XDG_CONFIG_HOME}`:

        Environment variable `XDG_CONFIG_HOME` is not set.

        Current value of `XDG_CONFIG_HOME` is `~/.config` (`/home/weihua/.config`).

    3.  Fcitx5 Settings Directory:

        Current fcitx5 settings directory is `~/.config/fcitx5` (`/home/weihua/.config/fcitx5`).

5.  Current user:

    The script is run as weihua (1000).

# Fcitx State:
1.  executable:

    Found fcitx5 at `/run/current-system/sw/bin/fcitx5`.

2.  version:

    Fcitx version: `5.0.16`

3.  process:

    Found 2 fcitx5 processes:

           3071 .fcitx5-wrapped
         129697 fcitx5-diagnose

4.  `fcitx5-remote`:

    `fcitx5-remote` works properly.

5.  DBus interface:

    Using `dbus-send` to check dbus.

    Owner of DBus name `org.fcitx.Fcitx5` is `:1.4`.

    PID of DBus name `org.fcitx.Fcitx5` owner is `3071`.

    Debug information from dbus:

           Group [x11::0] has 1 InputContext(s)
          IC [71992863fa0c4673ad16af4cd63d9ca2] program:slack frontend:dbus cap:6000000012 focus:0
        Group [wayland:] has 8 InputContext(s)
          IC [281aad5ac5264e6a8512cb54d4f2671f] program:emacs frontend:dbus cap:e001000052 focus:0
          IC [6d151c74967b41a9a34ccd95227b84f4] program:emacs frontend:dbus cap:e001000052 focus:0
          IC [118578a9011c4311a844a60bd46463cc] program:.telegram-desktop-wrapped frontend:dbus cap:e801800072 focus:0
          IC [d0e79014e7f440ef8cd942f086c84776] program:firefox frontend:dbus cap:6001000012 focus:0
          IC [7c5477ad6cae4524a5523b7f80358ac8] program:firefox frontend:dbus cap:e001000052 focus:0
          IC [21686454498b480dadaab3baec251a1a] program:firefox frontend:dbus cap:6001000012 focus:0
          IC [b39eec455e154cd1b9b5ca26cb0b144c] program:firefox frontend:dbus cap:6001000012 focus:0
          IC [f937896debf6483c9d63aa411225466e] program: frontend:wayland_v2 cap:100000052 focus:1
        Input Context without group

# Fcitx Configure UI:
1.  Config Tool Wrapper:

    Found fcitx5-configtool at `/run/current-system/sw/bin/fcitx5-configtool`.

2.  Config GUI for qt:

    Found `fcitx5-config-qt` at `/run/current-system/sw/bin/fcitx5-config-qt`.

3.  Config GUI for kde:

    **`kcmshell5` not found.**

# Frontends setup:
## Xim:
1.  `${XMODIFIERS}`:

    Environment variable XMODIFIERS is set to "@im=fcitx" correctly.
    Xim Server Name from Environment variable is fcitx.

2.  XIM_SERVERS on root window:

    **`xprop` not found.**

3.  XIM for Emacs:

    **Your LC_CTYPE is set to en_US.UTF-8 instead of one of zh, ja, ko. You may not be able to use input method in emacs because of an really old emacs bug that upstream refuse to fix for years.**

## Qt:
1.  qt4 - `${QT4_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

2.  qt5 - `${QT_IM_MODULE}`:

    Environment variable QT_IM_MODULE is set to "fcitx" correctly.

3.  Qt IM module files:

    **Cannot find fcitx5 input method module for Qt4.**
    **Cannot find fcitx5 input method module for Qt5.**

## Gtk:
1.  gtk - `${GTK_IM_MODULE}`:

    Environment variable GTK_IM_MODULE is set to "fcitx" correctly.

2.  `gtk-query-immodules`:

    1.  gtk 2:

        **Cannot find `gtk-query-immodules` for gtk 2**

        **Cannot find fcitx5 im module for gtk 2.**

    2.  gtk 3:

        **Cannot find `gtk-query-immodules` for gtk 3**

        **Cannot find fcitx5 im module for gtk 3.**

3.  Gtk IM module cache:

    1.  gtk 2:

        Found immodules cache for gtk `2.24.32` at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        **Failed to find fcitx5 in immodule cache at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        Found immodules cache for gtk `2.24.32` at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/i386-linux-gnu/libgtk2.0-0/gtk-query-immodules-2.0 from gtk+-2.24.32

        **Failed to find fcitx5 in immodule cache at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/i386-linux-gnu/gtk-2.0/2.10.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 2 in cache.**

    2.  gtk 3:

        Found immodules cache for gtk `3.24.5` at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.5

        **Failed to find fcitx5 in immodule cache at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache`**

        Found immodules cache for gtk `3.24.5` at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache`.
        Version Line:

            # Created by /usr/lib/i386-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0 from gtk+-3.24.5

        **Failed to find fcitx5 in immodule cache at `./.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20220601.0/files/lib/i386-linux-gnu/gtk-3.0/3.0.0/immodules.cache`**

        **Cannot find fcitx5 im module for gtk 3 in cache.**

    3.  gtk 4:

        **Cannot find immodules cache for gtk 4**

        **Cannot find fcitx5 im module for gtk 4 in cache.**

4.  Gtk IM module files:

    1.  gtk 2:

        All found Gtk 2 immodule files exist.

    2.  gtk 3:

        All found Gtk 3 immodule files exist.

    3.  gtk 4:

        All found Gtk 4 immodule files exist.

# Configuration:
## Fcitx Addons:
1.  Addon Config Dir:

    Found fcitx5 addon config directory: `/nix/store/8y2yd8iz044agrf7dmgj6y9ydr944c4j-fcitx5-5.0.16/share/fcitx5/addon`.

2.  Addon List:

    1.  Found 19 enabled addons:

            Classic User Interface 5.0.16
            Clipboard 5.0.16
            DBus 5.0.16
            DBus Frontend 5.0.16
            Emoji 5.0.16
            Fcitx4 Frontend 5.0.16
            IBus Frontend 5.0.16
            Input method selector 5.0.16
            Keyboard 5.0.16
            KDE Input Method Panel 5.0.16
            Status Notifier 5.0.16
            Notification 5.0.16
            Quick Phrase 5.0.16
            Spell 5.0.16
            Unicode 5.0.16
            Wayland 5.0.16
            Wayland Input method frontend 5.0.16
            XCB 5.0.16
            X Input Method Frontend 5.0.16

    2.  Found 0 disabled addons:

3.  Addon Libraries:

    All libraries for all addons are found.

4.  User Interface:

    Found 2 enabled user interface addons:

        Classic User Interface
        KDE Input Method Panel

## Input Methods:
1.  `/home/weihua/.config/fcitx5/profile`:

        [Groups/0]
        # Group Name
        Name=Default
        # Layout
        Default Layout=us
        # Default Input Method
        DefaultIM=rime

        [Groups/0/Items/0]
        # Name
        Name=keyboard-us
        # Layout
        Layout=

        [Groups/0/Items/1]
        # Name
        Name=rime
        # Layout
        Layout=

        [GroupOrder]
        0=Default

# Log:
1.  `date`:

        Sat Jul  2 09:17:19 PM CST 2022

2.  `/home/weihua/.config/fcitx5/crash.log`:

    `/home/weihua/.config/fcitx5/crash.log` not found.

**Comment by wengxt** [comment]
For issue on emacs, it's fixed in fcitx5-gtk master, see for more information: https://github.com/fcitx/fcitx5-gtk/issues/19

**Comment by weihua-lu** [comment]
@wengxt I can confirm emacs issue is gone with latest fcitx5-gtk master. Thanks.
Still not able to get candidate prompt with gnome terminal though, I guess that's a different issue then?

**Comment by wengxt** [comment]
since you’re using nix, I’d suspect it’s either missing some package or a nix specific bug (like fail to set certain path)

does your terminal app use gtk4?

**Comment by weihua-lu** [comment]
It's using gtk3, i tried with this [guide](https://wiki.gnome.org/Apps/Terminal/Debugging) to start a separate instance and the candidate prompt window can actually show up properly. I suspect this is a nix specific issue then which I'll proceed from nix side. Thanks for your time and help!
